### ISSUE TITLE
Adding `creator` etc. to the Object

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/deer#24]
The regular DEER record will add a `name` to it if `DEER-ENTITYNAME` is defined in the config file, but perhaps there should be an available array of selectors to configure so things like `creator` or other important information can be added explicitly to the authoritative object.

Thoughts @thehabes ?

**Comment by thehabes** [comment]
This is a good idea and we should look at it in the future.  Some things, especially those that would never change, should be able to be a part of an object directly.

**Comment by cubap** [comment]
not quite

**Comment by cubap** [comment]
Patrick Cuba  3:33 PM
creator is "testMachine" for everything, so it doesn't matter who did this.






Habes  3:34 PM
:disappointed:
3:34
damn.  We would have to fix that.
3:36
Ah it is becase setUserAttribution() populates creator in the forms, but not the DEER.ATTRIBUTION setting
3:37
deer-record.js needs DEER.ATTRIBUTION to be set appropriately..
3:38
So does that mean for the creator annotation?
3:39
Oh i see.  The creator annotation for the entity is correct.  The creator key:val pair to attribute the annotation is incorrect.

Patrick Cuba  3:39 PM
yup

Habes  3:40 PM
HMMMM want me to change that real fast, should be an easy fix

Patrick Cuba  3:40 PM
It's easy unless it breaks something. I'd say ticket it unless you want to chase it down today.

Habes  3:41 PM
I do not have any logic tied to annotation.creator
3:41
That just isn't a filter in Lived Religion yet

Patrick Cuba  3:41 PM
Is ATTRIBUTION something you made? What is it for?
3:42
Annotations don't have to have a creator, but an interface may do that.

Habes  3:43 PM
I don't think I made it, or at least I don't remember.  It is a config in DEER so that deer-record.js can attribute items by default

Patrick Cuba  3:43 PM
It looks like maybe I did it as a fallback...

Habes  3:43 PM
It is a fallback, and as you said, an interface is in charge of doing that

Patrick Cuba  3:43 PM
I am looking at #24. I'll think about it

Habes  3:43 PM
our interface was not
3:43
it is our interfaces fault
3:44
It assumed annotating a creator onto an entity would be the only level of attribution it needs.
3:45
However, if we want to tie descriptive data to a specific user, then attribution is required at annotation creation as well

Patrick Cuba  3:45 PM
The __rerum already has an Agent, so adding a creator should add information
3:45
I think the interface will need to do that, but I want to look at how the setting is used right now.

Habes  3:45 PM
For sure
3:46
My holistic understanding of it has holes

Patrick Cuba  3:46 PM
https://github.com/CenterForDigitalHumanities/deer/search?q=R.ATTRIBUTION&unscoped_q=R.ATTRIBUTION
3:46
It's definitely just a dumb addition of creator to Annotations

Habes  3:47 PM
yes
3:47
Is the __rerum agent reliable?
3:47
Like the name annotations we made have separate ones right?

Patrick Cuba  3:47 PM
__rerum is based on the token, so the same app will always make the same generatedBy
3:48
But being logged into LR has no effect
3:48
https://www.w3.org/TR/annotation-model/#h-other-properties
3:49
That's why I had added creator. Maybe we need to leave it and make some helpers for settign it better? Or document that an interface should have a hidden field for creator?

Habes  3:50 PM
Yes __rerum.generatedBy will be the same for everything generated by Lived Religion.  To attribute to users within Lived Religion, a creator must be known for each entity and annotation.
3:51
I thought adding a <input type="hidden" deer-key="creator" /> to each form would be enough to attribute the information created.  That only applies to entities though, not to individual annotations

Patrick Cuba  3:51 PM
Right, the LR interface should be updating a creator field (which will add to an entity on generation) and that should be detected for adding a creator to the Annotations on it as well.

Habes  3:51 PM
Yep
3:52
DEER will do it for free if I set DEER.ATTRIBUTION

Patrick Cuba  3:52 PM
Is that the best way? for a login action on LR to set a global config constant for DEER?
3:52
I don't mind it, I just want to be thoughtful

Habes  3:53 PM
LR.utils.setUserAttributionFields() fires on page load to populate all creator inputs
3:53
I feel like that should do it

Patrick Cuba  3:53 PM
But those inputs aren't set on the annotations
3:53
Because annotations have no "primitives"

Habes  3:53 PM
No, but that could be the moment Lived Religion sets DEER.ATTRIBUTION
3:54
Essentially, on page load, check for a logged in user.  If there is one, let that be the value of DEER.ATTRIBUTION for the page.  When timeout/logout occurs, all CRUD operations are rejected and the page is reloaded, so it should fit in to the flow of things

Patrick Cuba  3:55 PM
That sounds reasonable.

Habes  3:56 PM
Right?  If I do that in one tab, it doesn't affect the other tab right?

Patrick Cuba  3:56 PM
Your logout watcher would fire across tabs if you tried.

Habes  3:57 PM
Thats true

Patrick Cuba  3:58 PM
The create() in deer-record.js takes attribution as an argument, so you could always call it with that parameter to override the default or change the configuration for the default.
3:58
I'm a little worried that altering a config setting is bad practice, but I haven't thought through it yet.

Habes  3:58 PM
Oh i see I don't have access to the DEER object on the html pags
3:58
pages
3:58
I don't want to use the config setting
3:59
I want to use an LR setting, like LR.APPAGENT
3:59
but LR.LOGGEDINUSERAGENT

Patrick Cuba  3:59 PM
Right, we would need a setter in DEER to let people access it, that's what I was trying to say earlier

Habes  3:59 PM
LR.THISISTHELOGGEDINUSERANDYOUSHOULDUSETHISIDTOATTRIBUTEANNOTATIONS
3:59
lol
4:00
Sorry sorry I thought I had that encapsulated in the LR object.  My bad
4:01
Now I am with you.  So DEER is going to use 'testUser' every time unless deerInitializer.js in my app says "I have a logged in user, and I have the DEER settings, so initalize DEER with the logged in user I know for DEER.ATTRIBUTION

Patrick Cuba  4:01 PM
We have a create() in deer-record.js, but it doesn't look like it is used anywhere. I may have to chase this down more. I'll reopen the ticket.
