### ISSUE TITLE
simple type upsert error

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/deer#39]
This is a blocking issue for the Lived Religion project and must be resolved to get through https://github.com/CenterForDigitalHumanities/deer-LR/issues/41.

I am getting an error in the console `Uncaught TypeError: Cannot read property 'bind' of undefined   deer-record.js:208`

Upon tracking, I believe bind() is not being used correctly, or perhaps the scope of `this` is something different.  

```javascript
return this.simpleUpsert(event).bind(this).then(entity => {
     this.elem.setAttribute(DEER.ID, entity["@id"])
     new DeerReport(this.elem)
})
```

**Comment by thehabes** [comment]
Should the `.bind(this)` come after the `then(entity => {})`?  That seems to be how it is used in other places in the code instead of in `Promise`s (`simpleUpsert` returns a `Promise`)

**Comment by thehabes** [comment]
To replicate, visit http://lived-religion-dev.rerum.io/deer-lr/experience.html.  Start an experience by filling out the initial form, then click [Bodies] to reveal those form.  Practices and Senses are typed as `simple` and throw this error upon submission.

**Comment by cubap** [comment]
> Should the `.bind(this)` come after the `then(entity => {})`? That seems to be how it is used in other places in the code instead of in `Promise`s (`simpleUpsert` returns a `Promise`)

That seems right. I still don't have my machine, so if you can confirm taht this change is working, go ahead and push it through. I'll go home and do it if I cannot find Haroon this afternoon.

**Comment by thehabes** [comment]
Ok, I need to eat, I am at a good stopping point.  I will try this change after lunch and let you know how it goes.

**Comment by thehabes** [comment]
That was not it.  it appear this.simpleUpsert() returns undefined and I don't know why.  This is becoming increasingly difficult and time consuming.

**Comment by thehabes** [comment]
The callback structure is messed up. ` simpleUpsert()` returns a fetch for each annotation being created, and thus has multiple returns which is not understood by `processRecord`.  `simpleUpsert()`needs to build and return a promise Array that we can do Promise.all() on or something to be asynchronous effectively.

**Comment by cubap** [comment]
Okay. Let's put it on a shelf. I don't want to open anything up with this little time to spend on it. My desktop has just been pronounced dead, so it'll be after break before I can just work on something. As it is, I need to head home soon to get some TPEN projects merged from home.
________________________________

**Comment by thehabes** [comment]
Alright, then I am going to move foward with pushing the Lived Religion bodies-in-experience branch towards master, knowing that adding `Bodies` artifacts is not working due to this blocking issue.  I am fine with that, and it will be my excuse to move on to https://github.com/CenterForDigitalHumanities/deer-LR/issues/70.

**Comment by thehabes** [comment]
When in processRecord the .bind(this) call is superfluous and it is causing an undefined error.

Once I took care of that, I noticed that when I do deer-item-type=simple, a version of that object gets saved for each input, which is causing all sorts of issues when trying to query for that object, since I get representations I do not expect.
