### ISSUE TITLE
Programmatically $isDirty inputs

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/deer#64]
spawned from #63

**Comment by cubap** [comment]
@thehabes I'm making a redundant fix for this, but it should be working anyway. At the end of `processRecord()` (and within it in a few logic branches) the hard `new Deer Report(this.elem)` should be calling  `$isDirty = false` in the constructor. That should be fixing this. Can you confirm that this line is somehow not firing?

**Comment by thehabes** [comment]
That line at the end of `processRecord()` does fire, and fires for both Form A and Form B.

`$isDirty = false` in the constructor is for the `DeerReport`, no the `inputs` in the `DeerReport.elem`

Does that makes sense?

**Comment by thehabes** [comment]
In other words, `DeerReport.$isDirty` is imposed by the constructor.  The constructor has nothing to do with
`forEach(DeerReport.elem.input)`

**Comment by cubap** [comment]
Got it

**Comment by thehabes** [comment]
hooray!

**Comment by thehabes** [comment]
That is why `form.$isDirty = true` is not a good thing to do.  The form is the element of the DeerReport.  forms themselves are never dirty, only DeerReports and inputs.
