### ISSUE TITLE
makeDirty() helper 

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/deer#65]
DEER should have a registered helper event to use when making the DEER input of a DEER form programatically dirty.  

Instead of developers being expected to employ the solution #63, there could be a  `makeDirty` Event driven solution that is not tied to the reserve javascript `oninput` Event.  Having to use javascript's `oninput` Event means all `oninput` functionality will be employed when using it, which could have unintended consequences.

**Comment by cubap** [comment]
`el.addEventListener('input', (e) => e.target.$isDirty = true)` in `deer-record.js`

This is added in expand() as a listener and not `oninput` so it may be registered twice...

**Comment by thehabes** [comment]
Yes.  I have realized something important. 

`elem.oninput = event => this.$isDirty = true` 
In the  DeerReport constructor means that every input inside a DEER form, even inputs that are not deer inputs (AKA lack `elem.attribite(DEER.KEY)`), would make `DeerReport.$isDirty = true`.  This is not correct logic.

That means

```javascript
if (deerKeyValue) {
       //Then this is a DEER form input.
      el.addEventListener('input', (e) => e.target.$isDirty = true)
.
.
.
}
```
is actually the right place for it.  Not sure if we have to account for both `input` and `oninput` here.

Since that only happens in DEER forms with a set deer-id, how do we handle this when the the DEER form didn't have a deer-id?
```javascript
Array.from(this.inputs).forEach(inpt => {
        if (inpt.getAttribute(DEER.KEY)) { inpt.addEventListener('input', (e) => e.target.$isDirty = true) }
         if (inpt.type === "hidden") { inpt.$isDirty = true }
})
```

methinks that needs to be removed from the constructor.  Do that in #66.
