### ISSUE TITLE
deer-context array support

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/deer#77]
It is a basic right to apply multiple linked data contexts to any data generated.  `deer-context` should support being a string URL or an array of string URLs.  

contexts can be more than just an array of string URLs.  They can also include entries in the array like 

 `@version :1.1` ,
 `"dcterms": "http://purl.org/dc/terms/"`, 
```JSON
"format": {
   "@id": "http://purl.org/dc/terms/format"
}
```
or even scoped contexts, which go yet another object layer deeper.

I do not think DEER should support those kinds of entries in the array.  However, `["http://www.example.org/bryanContext.json", "https://www.otherexample.org/patrickContext.json"]` should be supported.  This is how third party developers using DEER can control the LD vocabulary required to properly describe and their data and the LD processing version.  Remember that we have array support already through `INPUTTYPE: "deer-input-type"`.

See https://www.w3.org/2018/jsonld-cg-reports/json-ld/#advanced-context-usage for more info on using multiple contexts.

**Comment by cubap** [comment]
Support stuff like http://jsfiddle.net/d8hfv9a3/1/ but not full objects and don't require extra attributes. If it is wrapped in "[...]" try to split it into strings (look for comma and encoded commas between `"` or `'` or `'/s'` or `"/s"` or encoded versions of that or escaped versions of that. Just handling this one thing is quite a lift since the `getAttribute()` can be a little unexpected.

**Comment by thehabes** [comment]
Notes on this from stand-up

- It is possible to allow users to put in JSON literals and JSON parse. Knowing this, instead of checking for a "string representing an array", we could simply JSON parse it, setting up logic for the future of handling JSON literals.
- We WILL NOT support supplying JSON literals for this fix for the LR sprint. They will be treated as strings.
- DO NOT check if it is a "string representing an array" by checking for delimiters. value="" is treated differently in this case than the multi select case. value="1, 2, 3" will not be considered an array. The syntax for sett deer-context will revolve around detecting [ and ] and the delimiter will always be a comma. Be careful with URLs that contain a comma...

**Comment by cubap** [comment]
These should work:
```html
<deer-form deer-context="string"></deer-form>
<deer-form deer-context="['string']"></deer-form>
<deer-form deer-context='["string"]'></deer-form>
<deer-form deer-context="['st','ri','ng']"></deer-form>
<deer-form deer-context="['st', 'ri', 'ng']"></deer-form>
// TODO: encoded versions
```

Not these (will just save a bunk string):
```html
<deer-form deer-context="[string]"></deer-form>
<deer-form deer-context="['st'|'ri'|'ng']"></deer-form>
<deer-form deer-context='[st,ri,ng]'></deer-form>
```

**Comment by thehabes** [comment]
I remember coming across this with the other stuff.

```javascript
let a = "['a','b','c']"
let b = '["a","b","c"]'
let c = "['a,b', 'b,c']"

let a_processed = a.slice(1, a.length-2).split(",")
let b_processed = b.slice(1, b.length-2).split(",")
let c_processed = c.slice(1, c.length-2)
c_processed = encodeURI(c_processed)
c_processed = c_processed.split(",")

a_processed
["'a'", "'b'", "'c'"]

b_processed
[""a"", ""b"", ""c""]

c_processed
["'a", "b'", "%20'b", "c"]
```

This is why we did not use brackets to represent the array when doing things like multi select.  To get around all this madness, I make the HTML look like the example below as entries get added to the attribute

```HTML
<deer-form deer-context="string"></deer-form>
<deer-form deer-context="st,ri,ng"></deer-form>
```
So if we want to support brackets being the switch, the values in the HTML need to look like

```HTML
<deer-form deer-context="[string]"></deer-form>
<deer-form deer-context="[st,ri,ng]"></deer-form>
```

String representation of arrays including brackets are extremely difficult to convert to a normalized array.  That said, I think

```HTML
<deer-form deer-context="[string]"></deer-form>
<deer-form deer-context='[st,ri,ng]'></deer-form>
```

Are the ones I am actually looking to support at this time.

**Comment by thehabes** [comment]
This does get us when comma is actually used as part of a value as opposed to a delimiter...

```javascript
let a = "a, b, c"
let b = 'a, b, c'
let c = "'a,b, b,c'"

a.split(",")
["a", " b", " c"]

b.split(",")
["a", " b", " c"]

c.split(",")
(4) ["a", "b", " b", "c"]

```
However, in these cases, since they are URLs, they are subject to...

2.2. Reserved Characters

Many URI include components consisting of or delimited by, certain special characters. These characters are called "reserved", since their usage within the URI component is limited to their reserved purpose. If the data for a URI component would conflict with the reserved purpose, then the conflicting data must be escaped before forming the URI.
```
 reserved    = ";" | "/" | "?" | ":" | "@" | "&" | "=" | "+" |"$" | ","

The "reserved" syntax class above refers to those characters that are allowed within a URI, but which may not be allowed within a particular component of the generic URI syntax.

So if a user has a `,` in their URL, it must be encoded.  We can presume, then, that what we actually need to support for c is
```javascript
let c = "a%2Cb, b%2Cc"
c.split(",")
["a%2Cb", " b%2Cc"]
```

So I really feel like, for now, the syntax we will actually support is 

```HTML
<deer-form deer-context='string'></deer-form>
<deer-form deer-context="string"></deer-form>
<deer-form deer-context="[string]"></deer-form>
<deer-form deer-context="[st,ri,ng]"></deer-form>
<deer-form deer-context='[st,ri,ng]'></deer-form>
<deer-form deer-context="[s%2Ct, r%2Ci, ,n%2Cg]"></deer-form>
<deer-form deer-context='[s%2Ct, r%2Ci, ,n%2Cg]'></deer-form>
```

It is on the dveloper to use the supported syntax, and if they do something foolish like 
<deer-form deer-context="[s,t, r,i, ,n,g]"></deer-form>
Then they will not end up with what they expect.  We can have an escape/unescape helper that tries to handle this for them, but that is extra and outside the scope of this solution.

**Comment by thehabes** [comment]
I know why you want to do it how you want by checking for encoding and brute force encoding off of assumptions between characters, but that is `1.5`, not `1.0` in my mind.

**Comment by thehabes** [comment]
Post Conversation Notes
Support the stringified whole array is desired, but cannot be accomplished within the timeframe of this sprint.  Escaping back and forth is a nightmare.  At the same time, deer-context as an array is a special case of array data and should not be handled the same way as the multiselects.

A middle ground solution...support this syntax

```HTML
<deer-form deer-context='URL'></deer-form>
<deer-form deer-context="URL"></deer-form>
<deer-form deer-context="[URL]"></deer-form>
<deer-form deer-context='[URL]'></deer-form>
<deer-form deer-context="[URL][URL]"></deer-form>
<deer-form deer-context='[URL][URL]'></deer-form>
```
This dissociates us from regular delimiter processing.  The one weakness it leaves is  if there is inappropriate use of `]` by those creating the URLs, then processing them into Arrays will not result in the intended arr. 

Example  
`<deer-form deer-context='[URL_1][UR]L_2][URL_3]'></deer-form>`
It would be impossible to know what the user intended the resulting array to look like.  It is most likely, to make this not crash, that  `L_2]` would be ignored.  The resulting array would be something like `["URL_1", "UR", "URL_3"]`

**Comment by thehabes** [comment]
```javascript
let b = "[1][2]][[3]"

b.match(/(?<=\[)(.*?)(?=\])/g)
["1", "2", "[3"]
b.match(/[^\[]+(?=\])/g)
["1", "2]", "3"]
```
If we are going to use Regex, one way or another brackets that cause trouble are going to dropped (depending on whether you are looking forwards or backwards).  

For `b` above, I think optimally we want `["1", "2]", "[3"]` but I can only seem to really get the bad `2` OR the bad `3`, not the bad `2` AND the bad `3`.

Need a regex expert here!  I am moving forward with this one
```javascript
b.match(/(?<=\[)(.*?)(?=\])/g)
["1", "2", "[3"]
```
