### ISSUE TITLE
expand() not attaching annos to resource

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/deer#9]
Object going into expand is `http://devstore.rerum.io/v1/id/5cbdd3ace4b0511ce825256e`

There are 5 annotation targeting him.  findByTargetId() finds and returns them all

`http://devstore.rerum.io/v1/id/5cbf21c3e4b0511ce8252570`
`http://devstore.rerum.io/v1/id/5cbf21d1e4b0511ce8252572`
`http://devstore.rerum.io/v1/id/5cbf2209e4b0511ce8252574`
`http://devstore.rerum.io/v1/id/5cbf2211e4b0511ce8252576`
`http://devstore.rerum.io/v1/id/5cbf221ee4b0511ce8252578`

For each of these, when it gets to `Object.assign(obj, val)`
`obj` is the person object that came in
`val` is `{format:"a", langauge"b", value:{source:{citationSource:"x", citationNote:"anno's label", comment:"z"}, value:"d"}}`

Object coming out of expand is
```javascript
{
   @id: "http://devstore.rerum.io/v1/id/5cbdd3ace4b0511ce825256e",
   @type: "Person",
   format: "text/html",
   language: "de",
   name: "Marco Reus",
   value:{
      value:"last annotation's value" 
      source:{
          "citationNote":"last annotation's label",
          "citationSource":"The person @id",
           "comment": "Static Comment"
      }
   }
}
```
What I was expecting was
```javascript
{
   @id: "http://devstore.rerum.io/v1/id/5cbdd3ace4b0511ce825256e",
   @type: "Person",
   name: "Marco Reus",
   anno1:{anno:innards},
   anno2:{anno:innards},
   anno3:{anno:innards},
   anno4:{anno:innards},
   anno5:{anno:innards}
}
```

**Comment by cubap** [comment]
These are goofy annotations:

```json
{
    "type": "Annotation",
    "label": "Given Name",
    "schemaKey": "givenName",
    "body": {
        "value": "Marco",
        "format": "text/html",
        "language": "de"
    },
    "target": {
        "id": "http://devstore.rerum.io/v1/id/5cbdd3ace4b0511ce825256e"
}
```

It may be easier to see if the assumed `motivation: "describing"` as being on the root of the annotation. The `label` and `schemaKey` properties are not describing the `target`, but the `Annotation` itself. It is the `body` of the annotation that is added to the `target`. Because of this, each is overwriting the last and the pieces outside of the `body` are discarded.

We should be looking at:

```json
{
    "type": "Annotation",
    "body": {
        "givenName": { 
            "label": "Given Name",
            "value": "Marco",
            "format": "text/html",
            "language": "de"
        }
    },
    "target": {
        "id": "http://devstore.rerum.io/v1/id/5cbdd3ace4b0511ce825256e"
}
```

As additional style notes:

* the reason to objectify the value of `target` is usually to add `@type` and/or `label`/`name`, otherwise it isn't worth the extra load.
* `format` for a name should probably not be 'html' unless there is a compelling reason, since it could break other things trying to consume it.

**Comment by thehabes** [comment]
Usually annotations do not have a labels and schemaKey was just for me if I wanted to try something.  The form of annotation I took was one with a textual body which was probably a bad example annotation to start with. I didn't really care what the keys were inside of `body` I just wanted to see how they were handled so I didn't give them much consideration.

As long as DEER is generating annotations like 
```javascript
{
    "type": "Annotation",
    "body": {
        "givenName": { 
            "label": "Given Name",
            "value": "Marco",
            "format": "text/html",
            "language": "de"
        }
    },
    "target": {
        "id": "http://devstore.rerum.io/v1/id/5cbdd3ace4b0511ce825256e"
   }
}
```

Then I think it is safe to assume annotations will look like that.  What if someone else is generating annotations that don't take on a form like that though, are there guidelines to making sure the annotation is structured the right way so DEER could consume it?  

What if my DEER-LR had its own non-DEER interface that generated some annotations like

```javascript
{
    "type": "Annotation",
    "body": {
         "label": "givenName",
         "value": "Marco",
    },
    "target": {
        "id": "http://devstore.rerum.io/v1/id/5cbdd3ace4b0511ce825256e"
   }
}
```
knowing that is a normal annotation but not knowing DEER wouldn't be able to aggregate it to my resource because of the structure of annotation it is assuming?

**Comment by cubap** [comment]
We default to not only how Web Annotation is supposed to work, but also how a `rdf:describes` (strictly, here, `motivation:describing` interacts with the `target` only with the `body`. If there is a `value` of some type, then the rest of the `body` is metadata for the property. If there is no `value` (like `{ body: { givenName: Marco } }`) then the whole `body` is the value and added completely. Your sample may not add what you expect, but I contend that it is also not a sound Web Annotation as written.

**Comment by thehabes** [comment]
That works for me as long as there is a standard default and we note that in the Wiki, my goal was to make `motivation:describing` annotations which I did not do very well here, call it user error.  

For use case's sake, pretend I am a Marco Reus fanatic and also have a Marco Reus blog.  For each blog post I save it as a commenting textual body annotation that targets `http://devstore.rerum.io/v1/id/5cbdd3ace4b0511ce825256e` so they look like

```javascript
{
  "@context": "http://www.w3.org/ns/anno.jsonld",
  "id": "http://example.org/anno6",
  "type": "Annotation",
  "bodyValue": "Marco Reus is the best player because he has committed to sticking with Dortmund his entire career.",
  "creator":"/blogger/id/443544565"
  "target": "http://devstore.rerum.io/v1/id/5cbdd3ace4b0511ce825256e"
}
```
I read Web Annotation and discovered this was the Web Annotation way to save this annotation.

These annotations end up on my person because findByTargetId finds them.   They end up aggregated to my person object all messed up like.  Essentially my template ignored them because I wanted them to be on the object like `obj.anno` which is good because it made me breakpoint the template and realize I was not getting what I expected and it was easy to track back to findTargetById().  

Let's now pretend my template wanted to render a count of how many blog posts about Marco my blog has.  How could I expect them to be aggregated to my object in a way I could get a count?  Right now, I do not think I could do such a thing with the obj passed into the template.

**Comment by thehabes** [comment]
Perhaps I even saved it as
```javascript
{
  "@context": "http://www.w3.org/ns/anno.jsonld",
  "id": "http://example.org/anno6",
  "type": "Annotation",
  "body": {
    "type": "TextualBody",
    "value": "Marco Reus is the best player because he has committed to sticking with Dortmund his entire career.",
    "format": "text/plain"
  },
  "creator":"/blogger/id/443544565",
  "target": "http://devstore.rerum.io/v1/id/5cbdd3ace4b0511ce825256e"
}
```

I would still only end up with only one of them like I did with my bad describing annotations even those these are good commenting annotations.

**Comment by thehabes** [comment]
This may be too out there for this stage of development.  This is not in my way of working, I am going to delete my bad describing annotations and make good ones to move forward with form work.  

I guess the overarching theme of this is what should DEER do with the various user error annotations that findByTargetId() finds and attempts to aggregate onto a resource?  Are there certain annotations that `expand()` should ignore? How should findByTargetId aggregate good annotations that aren't necessarily `motivation:describing`?  Can DEER tell the difference on objects without `motivation` explicitly declared?  Just what are `water bears`?

**Comment by cubap** [comment]
This annotation is either telling the consumer to grab the target and apply that type, value and format to it (not a great interpretation) or to apply the `value` to it, understanding it as a TextualBody in plaintext. In either case, when the next annotation is applied, it overwrites the properties because it is asserting the same thing all over again with different values.

Something to consider for another issue, though, is how to handle things that we want to add into an array, instead of replacing.

**Comment by cubap** [comment]
or... update the annotations with better-formed versions!

**Comment by cubap** [comment]
And I would be for requiring a certain motivation unless the config file has a flag in it to be more generous.
